### ISSUE TITLE
eventsByYears service failing on second request

### ISSUE THREAD

**Issue by jscheeler** [pwcexc/18f#34]
@iaguirre I'm getting this error when I try to request the url a second time. (i.e. refresh the page). Could this be an issue with receiving the 429 status from the API? 

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (c:\dev\18f\node_modules\express\lib\response.js:718:10)
    at ServerResponse.send (c:\dev\18f\node_modules\express\lib\response.js:163:12)
    at ServerResponse.json (c:\dev\18f\node_modules\express\lib\response.js:249:15)
    at ServerResponse.send (c:\dev\18f\node_modules\express\lib\response.js:151:21)
    at ClientRequest.<anonymous> (c:\dev\18f\controllers\integrations\openFDA\index.js:256:21)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
```

**Comment by jscheeler** [comment]
This only seems to be an issue when doing an ajax request.

**Comment by iaguirre** [comment]
@jscheeler could this be a caching issue? 

Also getting "Error: Cannot find module 'jquery' from '/Users/iaguirre002/Dev/18f/public/js"

**Comment by jscheeler** [comment]
Still happening.
